# Generated by Django 5.1.7 on 2025-03-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_id", models.CharField(max_length=30, unique=True)),
                ("book_name", models.CharField(max_length=255)),
                ("author_name", models.CharField(blank=True, max_length=255)),
                ("cluster", models.IntegerField(default=0)),
                ("cluster_label", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("tags", models.TextField(blank=True)),
                ("chapters", models.IntegerField(default=0)),
                ("score", models.FloatField(default=0.0)),
                ("first_chapter", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
