# Generated by Django 5.1.7 on 2025-04-18 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webnovel", "0007_alter_book_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
