# Generated by Django 5.1.7 on 2025-03-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0002_cluster_tag_remove_book_cluster_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cluster",
        ),
        migrations.AddField(
            model_name="book",
            name="cluster",
            field=models.ManyToManyField(related_name="books", to="novels.cluster"),
        ),
    ]
