# Generated by Django 5.1.7 on 2025-04-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0004_book_created_at_book_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_chinese",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
